# Generated by Django 2.2.10 on 2020-09-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='name',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AlterField(
            model_name='spot',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
